spring:
  application:
    name: revolucion-atletica-backend
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  threads:
    virtual:
      enabled: true
  profiles:
    default: dev
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8081
  error:
    include-binding-errors: never
    include-message: never


